# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 534c64e4338754458a8e45a991bbd040ba2c2822a4f2c7b9f0be99ad53845452a6dca98e5e31b9b192e4494b9d7fdfa6bb2b18c5ec0ed6cf44ca33003cdcb117

test:
  secret_key_base: 057b5a47bca6e9aae6163512d1715684a272492ebe8d38aac868f120d281873795ed77b40af81b4a3ed9a5b8f4088e60892a228948b11c41261a484c110ca23b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
